name: Build Rust Linux Static Binary (Pricing Solver)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build static binary
        run: cargo build --release --target x86_64-unknown-linux-musl
        working-directory: "rust pricing"

      - name: Upload static binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-pricing-static
          path: rust pricing/target/x86_64-unknown-linux-musl/release/vrp_pricing
